name: infra-test

on:
  workflow_call:
    inputs:
      aws_role_duration:
        type: number
        default: 3600
      base_ref:
        type: string
        required: true
      emaildomain_suffix:
        type: string
        default: ""
      head_ref:
        type: string
        required: true
      pull_request_url:
        type: string
        required: true
      repository:
        type: string
        required: true
      skip_smoke_tests:
        type: boolean
        default: false
      subdomain_suffix:
        type: string
        required: true
      stack:
        type: string
        required: true
    secrets:
      aws_access_key_id:
        required: true
      aws_region:
        required: true
      aws_role_arn:
        required: true
      aws_secret_access_key:
        required: true
      pulumi_access_token:
        required: true

jobs:
  infra_test:
    name: infra test
    runs-on: ubuntu-latest
    steps:
      - name: resolve pr refs
        id: refs
        uses: eficode/resolve-pr-refs@v0.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: assume aws deployment role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ secrets.aws_region }}
          role-to-assume: ${{ secrets.aws_role_arn }}
          role-duration-seconds: ${{ inputs.aws_role_duration }}
          role-session-name: ${{ inputs.stack }}TestSession

      # Spin up current state
      - name: current state checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.base_ref }}
      - name: generate test stack yaml file
        run: |
          cp Pulumi.${{ inputs.stack }}.yaml Pulumi.${{ inputs.stack }}-test.yaml
          pulumi config set subdomain "$(pulumi config get subdomain --stack puroearth/${{ inputs.stack }})${{ inputs.subdomain_suffix }}" --stack puroearth/${{ inputs.stack }}-test
          pulumi config set email-domain-prefix "$(pulumi config get email-domain-prefix --stack puroearth/${{ inputs.stack }})${{ inputs.emaildomain_suffix }}" --stack puroearth/${{ inputs.stack }}-test
          pulumi config set skip-final-snapshot "true" --stack puroearth/${{ inputs.stack }}-test
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.pulumi_access_token }}
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: current state up
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: puroearth/${{ inputs.stack }}-test
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.pulumi_access_token }}

      # Preview changes
      - name: target state checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.head_ref }}
      - name: generate test stack yaml file
        run: |
          cp Pulumi.${{ inputs.stack }}.yaml Pulumi.${{ inputs.stack }}-test.yaml
          pulumi config set subdomain "$(pulumi config get subdomain --stack puroearth/${{ inputs.stack }})${{ inputs.subdomain_suffix }}" --stack puroearth/${{ inputs.stack }}-test
          pulumi config set email-domain-prefix "$(pulumi config get email-domain-prefix --stack puroearth/${{ inputs.stack }})${{ inputs.emaildomain_suffix }}" --stack puroearth/${{ inputs.stack }}-test
          pulumi config set skip-final-snapshot "true" --stack puroearth/${{ inputs.stack }}-test
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.pulumi_access_token }}
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: target state pulumi preview
        uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: puroearth/${{ inputs.stack }}-test
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.pulumi_access_token }}

      # Apply changes
      - name: target state pulumi up
        uses: pulumi/actions@v3
        id: changes
        with:
          command: up
          stack-name: puroearth/${{ inputs.stack }}-test
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.pulumi_access_token }}
        continue-on-error: true

      # Authenticate to ECR, required for running the smoke-tests
      - name: Login to private ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@446a798035445cdfd5111ad9a49f48d46083a170
        # Note: We're referencing the desired version by commit hash instead of version number,
        # since this newer version is not yet released and introduces required fixes we need.

      # Smoketest
      - name: Run smoke-tests
        id: test
        if: ${{ !inputs.skip_smoke_tests && steps.changes.outcome == 'success' }}
        run: yarn smoke-test
        continue-on-error: true

      # Report status
      - name: report status
        run: |
          STATE=failure
          if [[ "${{ steps.changes.outcome }}" == "success" && "${{ steps.test.outcome }}" == "success" ]]; then
            STATE=success
          fi
          SHA=$(git rev-parse HEAD)
          echo "Reporting status for commit $SHA"
          curl --request POST \
          --url "https://api.github.com/repos/${{ inputs.repository }}/statuses/$SHA" \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'accept: application/vnd.github.v3+json' \
          --header 'content-type: application/json' \
          --data "{
            \"state\": \"$STATE\",
            \"context\": \"infra-test\",
            \"target_url\": \"${{ inputs.pull_request_url }}\"
            }" \
          --fail
          if [[ "${{ steps.changes.outcome }}" != "success" ]]; then
            echo "pulumi failed to apply changes"
            echo "exit 1"
            exit 1
          elif [[ "${{ steps.test.outcome }}" != "success" ]]; then
            echo "smoketest failed"
            echo "exit 1"
            exit 1
          fi

      # Cleanup
      - name: pulumi destroy
        uses: pulumi/actions@v3
        with:
          command: destroy
          stack-name: puroearth/${{ inputs.stack }}-test
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.pulumi_access_token }}
