name: preview PR to main
on:
  workflow_call:
    inputs:
      aws_role_duration:
        type: number
        default: 1200
      stack:
        required: true
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_region:
        required: true
      aws_role_arn:
        required: true
      aws_secret_access_key:
        required: true
      pulumi_access_token:
        required: true
      GH_PACKAGES_TOKEN:
        required: true

jobs:
  preview:
    name: Preview on dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: assume aws deployment role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ secrets.aws_region }}
          role-to-assume: ${{ secrets.aws_role_arn }}
          role-duration-seconds: ${{ inputs.aws_role_duration }}
          role-session-name: deploymentSession

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      
      - name: Authenticate to GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${GH_PACKAGES_TOKEN}" >> ~/.npmrc
        env:
          GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - uses: pulumi/actions@v3
        name: Preview Pulumi for dev
        with:
          command: preview
          stack-name: puroearth/dev
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.pulumi_access_token }}
